name: NY
markdown: kramdown
kramdown:
  input: GFM
syntax-highlighting: true
highlighter: rouge
timezone: America/Los_Angeles
permalink: /blog/:year/:month/:day/:title
excerpt_separator: <!--end excerpt-->
syntax-highlighting:
   enabled: true
   css: syntax.css
