name: NY
timezone: America/Los_Angeles
permalink: /blog/:year/:month/:day/:title
excerpt_separator: <!--end excerpt-->
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

