name: NY
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
timezone: America/Los_Angeles
permalink: /blog/:year/:month/:day/:title
excerpt_separator: <!--end excerpt-->
